[package]
name = "vlc-module-check"
version = "0.1.0"
authors = ["Alexandre Janniaux <alexandre.janniaux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clang]
version = "0.22"
features = ["clang_8_0"]
